// Shared desktop shell for the home, life and town entry points.
const townBoot=document.getElementById('gameBoot');
document.body.innerHTML = `
<div class="small-screen-note">本作按桌面游戏设计，建议使用电脑或横屏游玩。</div>
<div class="game-shell">
  <header class="game-header"><a class="brand" href="index.html"><img class="brand-mark" src="favicon.svg" alt=""><span>栖迟小镇<small>A LITTLE TOWN, ANOTHER LIFE</small></span></a><div class="header-center"><span class="live-dot"></span><span id="worldTime">春日 · 晴</span><span class="header-divider">/</span><span>把日子，过成自己的故事</span></div><nav><button id="helpBtn">游玩指南</button><button id="muteBtn" aria-pressed="false">音效开</button><button id="directoryBtn">地点手册</button><button id="atlasBtn">旅途图鉴</button><button id="profileBtn">我的旅人</button></nav></header>
  <main class="game-layout">
    <aside class="character-pane panel"><div class="panel-kicker">你的这一生 <span>CHARACTER</span></div><div class="portrait-frame"><img src="assets/town/character.svg" alt="穿绿色外套的小镇旅人"><span class="portrait-badge">旅人</span></div><h1 id="characterName">故事还没有开始</h1><p id="characterSubtitle" class="muted">一座小镇，无数种活法。</p>
      <section id="run" class="hidden"><div class="run-context"><span id="runIdentity"></span></div><div id="resources" class="resource-grid" aria-live="polite"></div><div class="section-label">随身天赋</div><div id="runTalents" class="run-talents"></div><button id="abandon" class="text-button">重新开始这段人生</button></section>
      <div id="idleStats"><div class="empty-resource"><span>体力</span><i></i><b>—</b></div><div class="empty-resource"><span>财富</span><i></i><b>—</b></div><div class="empty-resource"><span>心情</span><i></i><b>—</b></div><div class="empty-resource"><span>学识</span><i></i><b>—</b></div><p class="muted">挑选出身与天赋，<br>带着你的第一副牌出发。</p></div>
      <div class="character-bottom"><button id="bagBtn" class="utility-button">▧ 随身物品 <span id="bagCount">0</span></button><button id="collectionBtn" class="utility-button">✦ 人生回声 <span id="collectionCount"></span></button></div>
    </aside>
    <section class="world-pane"><div class="world-heading"><div><span class="location-dot"></span><strong>栖迟小镇</strong><span class="muted">一切故事的起点</span></div><span class="world-coordinate">固定地图 · 01</span></div><div class="world-stage"><div class="world-viewport"><canvas id="worldCanvas" width="1000" height="700" aria-label="固定小镇场景，点击地面行走，也可用方向键移动并按 E 互动" role="img" tabindex="0"></canvas><div id="scenePlaces" class="scene-places"></div><div class="world-caption"><span class="live-dot"></span><span id="sceneHint">小镇一直在这里，等你开始新的故事。</span></div><p id="walkStatus" class="walk-status" role="status" hidden></p><button id="nearbyInteraction" class="nearby-interaction" hidden></button><button id="launch" class="launch-card"><span class="launch-symbol">↗</span><span><strong id="launchTitle">开始一段新的人生</strong><small id="launchDescription">选出身 · 搭天赋 · 写下你的故事</small></span><b id="launchAction">出发</b></button></div></div>
      <div class="journey-bar"><div id="stageTrack" class="stage-track" aria-label="人生阶段"></div><span id="journeyProgress">尚未启程</span></div>
      <section id="routeView" class="route-console hidden"><div><span class="section-label">今天去哪里</span><strong id="stepText"></strong></div><div id="routes" class="route-grid"></div></section>
      <div id="idleConsole" class="idle-console"><span>慢一点，也可以走得很远。</span><small>点击地面行走，点击建筑会走到门口。</small></div>
    </section>
    <aside class="journal-pane panel"><div class="panel-kicker">人生手记 <span>JOURNAL</span></div><div class="journal-date"><span id="journalStage">序章</span><strong id="journalTitle">关于下一次出发</strong></div><p id="journalIntro">有些路走过才知道，有些选择会在很久以后回响。这里会记下你做出的每一个决定。</p><ol id="history" class="history"></ol><div class="journal-bottom"><span class="ink-mark">✳</span><p>每一段普通的日子，<br>也值得被好好记住。</p></div></aside>
  </main>
  <footer class="game-footer"><div><kbd>W A S D</kbd> / <kbd>方向键</kbd> 行走 <span>·</span><kbd>E</kbd> 进入建筑 <span>·</span> 点击地面行走 · 点击建筑前往</div><span id="saveState" role="status">存档保存在此浏览器</span><button data-tool="privacy">仅供娱乐 · 小镇公约</button></footer>
</div>
<dialog id="setupDialog" class="game-dialog setup-dialog" aria-labelledby="setupTitle"><button class="dialog-close" data-close="setupDialog" aria-label="关闭角色创建窗口">×</button><section id="setup"><p class="eyebrow">A NEW CHAPTER</p><h2 id="setupTitle">这一次，你想怎样开始？</h2><p class="dialog-lead">选择起点，带上天赋。接下来的故事，由你决定。</p><div id="resumeBox" class="inset hidden"><h3>上次的人生还没写完</h3><p id="resumeText"></p><div class="btn-row"><button id="resume" class="btn">继续这段人生</button><button id="discard" class="btn ghost">重新开始</button></div></div><div id="draftBox"><div class="step-heading"><span>01</span><h3>选择出身</h3><small>各有长短，没有标准答案</small></div><div id="origins" class="origin-grid"></div><div class="step-heading"><span>02</span><h3>带走两个天赋</h3><small id="talentCount"></small></div><p class="muted">四个候选，只带走两个。发现新结局，会解锁更多可能。</p><div id="talents" class="talent-grid"></div><button id="begin" class="btn begin-run" disabled>带着这副牌，出发 →</button></div><p id="unlockNote" class="muted"></p></section></dialog>
<dialog id="eventDialog" class="game-dialog event-dialog" aria-label="人生事件"><button class="dialog-close" data-close="eventDialog" aria-label="暂时回到小镇">×</button><div class="dialog-art"><span id="eventArt">一段新的经历</span><img id="eventScene" alt=""></div><section id="eventView" class="hidden"><p id="eventCategory" class="eyebrow"></p><h2 id="eventTitle"></h2><p id="eventText" class="story-text"></p><div id="choices" class="choice-list"></div><p class="choice-note">变化已包含天赋效果与本阶段体力消耗。</p></section><section id="outcomeView" class="hidden" aria-live="polite"><p class="eyebrow">这一刻，已经发生</p><h2 id="outcomeTitle"></h2><p id="outcomeText" class="story-text"></p><div id="outcomeDelta"></div><button id="continue" class="btn">继续人生 →</button></section><section id="endingView" class="ending-card hidden"><p class="eyebrow">这一生，写到了最后一页</p><div id="endingIcon"></div><h2 id="endingTitle"></h2><p id="endingText" class="story-text"></p><p id="endingUnlock"></p><div class="btn-row"><button id="copy" class="btn">复制人生故事</button><button id="download" class="btn ghost">下载结局卡</button><button id="again" class="btn ghost">再活一次</button></div></section></dialog>
<dialog id="collectionDialog" class="game-dialog collection-dialog" aria-labelledby="collectionTitle"><button class="dialog-close" data-close="collectionDialog" aria-label="关闭结局图鉴">×</button><p class="eyebrow">ECHOES OF A LIFE</p><h2 id="collectionTitle">不同人生的回声</h2><p class="dialog-lead">这些结局，是你曾经来过的证据。</p><p id="atlasSummary" class="muted"></p><div id="atlasTabs" class="atlas-tabs"></div><div id="endings"></div><div id="atlasGrid" class="atlas-grid hidden"></div><p class="muted">发现 1 种结局解锁“捡漏体质”；发现 3 种解锁“命运亲戚”。</p><p class="muted">签文、生肖、棋局与旧日故事，都收在同一本图鉴里。</p></dialog>
<dialog id="bagDialog" class="game-dialog" aria-labelledby="bagTitle"><button class="dialog-close" data-close="bagDialog" aria-label="关闭随身物品">×</button><p class="eyebrow">THINGS YOU KEEP</p><h2 id="bagTitle">随身物品</h2><p class="dialog-lead">你在故事中留下的线索，会在后来派上用场。</p><div id="bagItems"></div></dialog>
<dialog id="helpDialog" class="game-dialog" aria-labelledby="helpTitle"><button class="dialog-close" data-close="helpDialog" aria-label="关闭指南">×</button><p class="eyebrow">TAKE YOUR TIME</p><h2 id="helpTitle">欢迎来到栖迟小镇</h2><div class="help-grid"><p><strong>01 / 出发</strong>选择一种出身与两个天赋。每局四个候选天赋，不同结局会解锁新的候选。</p><p><strong>02 / 探索</strong>点击地面自动行走，点击建筑会先走到门口，选择“今日经历”推进人生，或选择闲逛活动。方向键 / WASD 可以随时接管行走，靠近建筑按 E 或点击互动提示；Esc 停止自动行走。移动与闲逛不消耗资源。</p><p><strong>03 / 选择</strong>亮起的建筑是本步可选路线。没做决定时，可关闭事件窗口重选路线。每阶段三次经历，共五个阶段；决定发生后自动保存，不能撤销。</p><p><strong>04 / 留下回声</strong>体力或心情耗尽会提前结束。结局只解锁候选天赋，不会永久加属性。</p></div><p class="muted">体力、心情、学识 0–100；财富 -100–200。每次经历的体力消耗依阶段为 3 / 4 / 5 / 4 / 3，选择预览已计入。结局按图鉴顺序判定。存档仅存在当前浏览器。</p><div class="btn-row"><button class="btn ghost" data-tool="life-classic">翻开旧日故事</button><button class="btn ghost" data-panel="profile">个人档案</button></div></dialog>
<dialog id="placeDialog" class="game-dialog" aria-labelledby="placeTitle"><button class="dialog-close" data-close="placeDialog" aria-label="关闭建筑窗口">×</button><p class="eyebrow">AROUND THE CORNER</p><h2 id="placeTitle"></h2><div class="place-intro"><img id="placeScene" alt=""><p id="placeText" class="story-text"></p></div><div id="placeActions" class="place-actions"></div><p id="placeRouteNote" class="choice-note"></p></dialog>
<dialog id="restartLife" class="game-dialog" aria-labelledby="restartLifeTitle"><h2 id="restartLifeTitle">放下这段人生？</h2><p class="story-text">当前进度会结束，不获得结局奖励。已经发现的结局会保留。</p><div class="btn-row"><button id="confirmLife" class="btn">重新开始</button><button id="cancelLife" class="btn ghost">继续这一局</button></div></dialog>
`;

if(townBoot)document.body.prepend(townBoot);
document.body.insertAdjacentHTML('beforeend', `
<dialog id="toolDialog" class="game-dialog tool-dialog" aria-labelledby="toolTitle"><header class="tool-heading"><img id="toolPortrait" alt=""><div><p class="eyebrow">小镇闲逛 · 不消耗本局资源</p><h2 id="toolTitle"></h2><p id="toolSubtitle"></p></div><button id="toolBack" class="btn ghost">返回小镇</button></header><p id="toolLoading" class="tool-loading" role="status">正在打开这扇门……</p><iframe id="toolFrame" title="小镇活动" src="about:blank"></iframe></dialog>
<dialog id="directoryDialog" class="game-dialog directory-dialog" aria-labelledby="directoryTitle"><button class="dialog-close" data-close="directoryDialog" aria-label="关闭地点手册">×</button><p class="eyebrow">EVERY DOOR HAS A STORY</p><h2 id="directoryTitle">小镇地点手册</h2><p class="dialog-lead">进一扇门，遇见一种生活。亮起的地点，可以推进今天的旅程。</p><div id="directoryPlaces" class="directory-grid"></div></dialog>
<dialog id="profileDialog" class="game-dialog profile-dialog" aria-labelledby="profileTitle"><button class="dialog-close" data-close="profileDialog" aria-label="关闭旅人档案">×</button><p class="eyebrow">THE TRAVELLER'S NOTE</p><h2 id="profileTitle">我的旅人</h2><div id="profileStats" class="profile-stats"></div><form id="travellerForm"><label>旅人昵称<input id="travellerName" maxlength="24" autocomplete="nickname" placeholder="怎么称呼你？"></label><label>生日 · 可选<input id="travellerBirth" type="date"></label><p class="muted">生日供排盘、人生刻度使用；昵称与生日不会改变本局角色资源。信息仅保存在当前浏览器。</p><p id="profileFeedback" class="form-feedback" role="status"></p><button class="btn" type="submit">保存旅人档案</button></form></dialog>
`);
