(function(){
  const D=NPCData,N=NPCSystem,E=NPCEvents,G=GameTime,$=id=>document.getElementById(id),make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  let activeRun=!!GameUI.residentState(),chessPartner=null,initial=GameUI.residentInitial,time=G.restore(initial?.time),world=N.create(GameUI.status().seed||0,initial?.world),clue=!!initial?.clue,previousSteps=initial?.steps||0,saveElapsed=0,approachElapsed=0,approach=null,selected=null,resting=false,idle=0;
  const clock=make('button','','town-clock');clock.id='townClock';clock.title='小镇时间随活动推进；打开窗口或离开页面会暂停。';document.querySelector('.world-stage').append(clock);
  const journal=make('button','人物志','resident-journal');journal.id='residentJournal';document.querySelector('.world-stage').append(journal);
  const dialog=make('dialog',undefined,'game-dialog resident-dialog');dialog.id='residentDialog';dialog.setAttribute('aria-labelledby','residentName');dialog.innerHTML='<button class="close resident-close" aria-label="关闭交谈">×</button><div class="resident-heading"><img id="residentPortrait" alt=""><div><h2 id="residentName"></h2><p id="residentRole"></p><small id="residentRelation"></small></div></div><p id="residentWords" class="resident-words"></p><div id="residentActions" class="resident-actions"></div><p id="residentNote" class="muted"></p>';document.body.append(dialog);dialog.querySelector('.resident-close').onclick=()=>dialog.close();
  const book=make('dialog',undefined,'game-dialog resident-book');book.id='residentBook';book.setAttribute('aria-label','小镇人物志');book.append(make('h2','小镇人物志'),make('p','认识一个人，也需要慢慢走过一些日子。','muted'));const cards=make('div',undefined,'resident-cards'),close=make('button','回到小镇','btn');close.onclick=()=>book.close();book.append(cards,close);const bookClose=make('button','×','resident-book-close');bookClose.setAttribute('aria-label','关闭人物志');bookClose.onclick=()=>book.close();book.prepend(bookClose);document.body.append(book);
  const question=make('button','？','resident-clue');question.hidden=true;question.setAttribute('aria-label','偷听到的线索：去山坡观星屋看看');question.onclick=()=>TownScene.visit('observatory');document.querySelector('.world-stage').append(question);
  function sync(){const s=GameUI.residentState(),seed=s?.seed||0,steps=s?LifeRogue.steps(s):0;if(seed!==world.seed||activeRun!==!!s||(steps<previousSteps)){activeRun=!!s;world=N.create(seed);time=G.restore();clue=false;previousSteps=0;approach=null;}if(steps>previousSteps){for(let i=previousSteps;i<steps;i++)G.next(time);previousSteps=steps;}return s;}
  function actor(id){return world.actors.find(a=>a.id===id&&!a.away);}
  function nearby(p){return N.near(world,p);}
  function canTalk(id){const a=actor(id),p=TownScene.snapshot().position;return a&&Math.hypot(a.x-p.x,a.y-p.y)<=55;}
  function button(label,fn){const b=make('button',label,'btn');b.onclick=fn;$('residentActions').append(b);}
  function talk(id,first=false){if(!canTalk(id)){showToast('走近这个居民再交谈。');return;}selected=id;const d=D.residents.find(d=>d.id===id),a=actor(id),s=sync(),line=NPCDialogue.line(id,s,time,a.behavior),m=E.memory(s,id);if(!m.metPlayer&&E.available(s,id).includes('meet')){LifeRogue.resident(s,id,'meet');GameUI.residentSave();}
    $('residentPortrait').src=TownRenderer.portrait(a.age,{coat:a.coat});$('residentPortrait').alt=d.name+'的头像';$('residentName').textContent=d.name;$('residentRole').textContent=a.role+' · '+D.behaviors[a.behavior];$('residentRelation').textContent=E.label(E.memory(s,id).relation);$('residentWords').textContent=line;$('residentActions').replaceChildren();
    const available=E.available(s,id);if(available.includes('chat'))button('坐着聊一会儿',()=>{if(canTalk(id)&&LifeRogue.resident(s,id,'chat')){GameUI.residentSave();talk(id);}});
    if(available.includes('help'))button('听听最近的事',()=>story(id,0));if(available.includes('done'))button('说起那件旧事',()=>story(id,1));
    if(['he','chen'].includes(id)&&E.memory(s,id).relation>=40)button('在棋盘边坐下',()=>{chessPartner=id;dialog.close();GamePanels.tool('gomoku');showToast(d.name+'：输赢不急，先落一子。');});
    button('再见，慢慢走',()=>dialog.close());$('residentNote').textContent=!s?'开启一段人生后，你们的相遇会记在这一局里。':s.version!==2?'这段旧版人生保持原来的规则；下一段人生会记下居民故事。':s.phase!=='route'?'先完成手上的人生经历，再和居民说说最近的事。':'闲聊不推进人生；有些相遇不会带来任何奖励。';GameUI.open('residentDialog');
  }
  function story(id,index){const s=sync(),row=E.stories[id][index],helped=E.memory(s,id).playerHelpedMe;$('residentWords').textContent=index===1&&!helped?'当年你没有参与那件小事，如今它已慢慢过去。'+row[1]:row[1];$('residentActions').replaceChildren();for(const [label,choice] of index===0?[[row[2],'help'],[row[3],'decline']]:[[row[2],'done']])button(label,()=>{if(!canTalk(id)||!LifeRogue.resident(s,id,choice)){showToast('这件事已经过去，或现在还不能发生。');return;}GameUI.residentSave();talk(id);});button('改天再说',()=>talk(id));}
  function entries(){const s=sync();return D.residents.map(d=>{const m=E.memory(s,d.id),p=N.profile(d,Math.min(4,s?.stage||0));return {name:m.metPlayer?d.name:'？？？',owned:m.metPlayer,icon:'book',text:!m.metPlayer?'还未认识的小镇居民。':p.role+' · '+E.label(m.relation)+(p.away?'\n暂时离开小镇求学。':'')+(m.relation>=40?'\n'+d.personality.join('、')+'。\n'+Object.entries(d.relationships).map(([id,label])=>D.residents.find(d=>d.id===id).name+'：'+label).join('；'):'\n还需要多聊聊，才能了解他的生活。')+(m.complete?'\n'+E.stories[d.id][1][0]+'：'+(m.playerHelpedMe?'旧事有了温暖的回音。':'你们也聊起当年的错过。'):'')};});}
  journal.onclick=()=>{cards.replaceChildren();for(const item of entries()){const card=make('article',undefined,'ending-entry'+(item.owned?'':' locked'));card.append(make('h3',item.name),make('p',item.text));cards.append(card);}GameUI.open('residentBook');};
  clock.onclick=()=>showToast('每 90 秒活动时间推进一个时段；人生每一步也会推进时间。在长椅边可以坐到下一时段。');
  const spots=[{id:'benchWest',name:'路边长椅',x:362,y:412,action:'坐下'},{id:'benchEast',name:'书屋长椅',x:594,y:412,action:'坐下'},{id:'notice',name:'公告栏',x:566,y:286,action:'看看'},{id:'water',name:'池塘边',x:770,y:615,action:'看水'}];
  const environment=make('dialog',undefined,'game-dialog resident-dialog');environment.setAttribute('aria-label','停一会儿');document.body.append(environment);
  function nearbySpot(p){return spots.find(v=>Math.hypot(v.x-p.x,v.y-p.y)<42);}
  function observe(spot){environment.replaceChildren(make('h2',spot.name),make('p',spot.id==='notice'?'公告栏贴着一张褪色的旧纸：书屋借阅，记得按时归还。角落有人写着“下周棋摊见”。':spot.id==='water'?'水面轻轻晃着。没有什么大事发生，只是风又吹过了一次。':'坐下来，看人慢慢走过。这里没有奖励，也不必急着出发。','resident-words'));const b=make('button',spot.action==='坐下'?'坐到下一时段':'再看一会儿','btn');b.onclick=()=>{resting=spot.action==='坐下';if(resting)G.next(time);environment.close();GameUI.residentSave();};const leave=make('button','继续走走','btn');leave.onclick=()=>environment.close();environment.append(b,leave);document.querySelectorAll('dialog[open]').forEach(d=>d.close());environment.showModal();}
  $('placeDialog').addEventListener('toggle',()=>{if(!$('placeDialog').open)return;const p=TownScene.snapshot().position;if(['park','chess','home'].some(id=>{const a=FixedTown.places.find(v=>v.id===id);return Math.hypot(p.x-a.x,p.y-a.y)<75;})){const b=make('button','坐一会儿 · 到下一时段','place-action');b.onclick=()=>{G.next(time);resting=true;GameUI.close('placeDialog');GameUI.residentSave();};$('placeActions').append(b);}});
  TownScene.residents={cancelApproach:()=>{approach=null;},actors:()=>world.actors,playerPose:()=>({sitting:resting,idleFacing:idle>10?(Math.floor(idle/4)%2?'left':'right'):null}),near:p=>{const a=nearby(p);return a?{...a,name:D.residents.find(d=>d.id===a.id).name}:null;},interact:p=>{const a=nearby(p);if(a){talk(a.id);return true;}return false;},click:(point,p)=>{const a=world.actors.find(a=>!a.away&&Math.abs(a.x-point.x)<19&&point.y<a.y+10&&point.y>a.y-60);if(!a)return false;if(Math.hypot(a.x-p.x,a.y-p.y)<=55)talk(a.id);else{approach=a.id;approachElapsed=0;TownScene.walkTo({x:a.x,y:a.y});}return true;},tick:(dt,paused,p)=>{const s=sync();G.tick(time,dt,paused);N.tick(world,time,Math.min(4,s?.stage??2),dt,paused);if(!paused){idle+=dt;saveElapsed+=dt;if(approach){approachElapsed+=dt;const target=actor(approach);if(!target||approachElapsed>20){approach=null;}else if(!TownScene.snapshot().goal&&!canTalk(approach))TownScene.walkTo({x:target.x,y:target.y});}if(approach&&canTalk(approach)){const id=approach;approach=null;talk(id);}if(!clue&&world.actors.some(a=>a.speech.includes('山坡')&&Math.hypot(a.x-p.x,a.y-p.y)<140)){clue=true;showToast('听见一条线索：山坡旧路最近有人走过。');GameUI.residentSave();}if(saveElapsed>=10){saveElapsed=0;GameUI.residentSave();}}},draw:(c,p,camera)=>{c.font='12px Microsoft YaHei';c.textAlign='center';for(const a of world.actors){if(a.away||Math.hypot(a.x-p.x,a.y-p.y)>150||(!a.speech&&nearby(p)?.id!==a.id))continue;const d=D.residents.find(d=>d.id===a.id),text=a.speech||d.name+' · '+D.behaviors[a.behavior];const width=Math.min(300,c.measureText(text).width+16);c.fillStyle='#f6eddbed';c.beginPath();c.roundRect(a.x-width/2,a.y-77-(D.residents.indexOf(d)%2)*25,width,22,8);c.fill();c.fillStyle='#61715c';c.fillText(text,a.x,a.y-62-(D.residents.indexOf(d)%2)*25);}if(idle>10){c.fillStyle='#f6eddb';c.fillText(resting?'坐一会儿':'… 看看四周',p.x,p.y-64);}if(clue){const pos=TownCamera.toScreen({x:1380,y:215},camera);question.hidden=pos.x<0||pos.x>1||pos.y<0||pos.y>1;question.style.left=pos.x*100+'%';question.style.top=pos.y*100+'%';}else question.hidden=true;},hud:cv=>{if(cv.dataset.moving==='true'){idle=0;resting=false;}clock.textContent='第 '+(time.day+1)+' 天 · '+G.slots[time.slot];clock.dataset.slot=time.slot;clock.dataset.paused=String(TownScene.pause());cv.dataset.residents=JSON.stringify(world.actors.filter(a=>!a.away).map(a=>({id:a.id,x:+a.x.toFixed(1),y:+a.y.toFixed(1),behavior:a.behavior,goal:a.goal?.place})));}};
  globalThis.ResidentUI={entries,snapshot:()=>{sync();return {time:G.restore(time),world:N.snapshot(world),clue,steps:previousSteps};},crossRunMemory:()=>null};
  window.addEventListener('message',event=>{if(event.source!==$('toolFrame').contentWindow||event.origin!==location.origin||event.data?.type!=='town:chess-result'||!chessPartner||!$('toolDialog').open||$('toolDialog').dataset.tool!=='gomoku')return;const id=chessPartner;chessPartner=null;if(LifeRogue.resident(sync(),id,'chess',event.data.moves)){GameUI.residentSave();showToast(D.residents.find(d=>d.id===id).name+'记住了这盘棋。');}});
  $('toolDialog').addEventListener('close',()=>{chessPartner=null;});
  if($('collectionDialog').open)GamePanels.atlas();
  const npcNear=TownScene.residents.near,npcInteract=TownScene.residents.interact,npcClick=TownScene.residents.click;
  TownScene.residents.near=p=>npcNear(p)||nearbySpot(p);
  TownScene.residents.interact=p=>{if(npcInteract(p))return true;const spot=nearbySpot(p);if(spot){observe(spot);return true;}return false;};
  TownScene.residents.click=(point,p)=>{if(npcClick(point,p))return true;const spot=spots.find(v=>Math.hypot(v.x-point.x,v.y-point.y)<24);if(!spot)return false;if(Math.hypot(spot.x-p.x,spot.y-p.y)<42)observe(spot);else TownScene.walkTo({x:spot.x,y:spot.y});return true;};
})();
