(function(root){
  const node=typeof module!=='undefined'&&module.exports,D=node?require('./npc-data.js'):root.NPCData;
  // Small authored chains; choices are replayed alongside life actions, never rolled again.
  const stories={
    lin:[['工坊的旧灯','林叔正拆一盏旧灯。“一个人扶不稳，你有空吗？”','帮他扶住灯架','先忙自己的事',{body:-3,knowledge:2},'linHelp'],['灯又亮了','多年后，旧灯仍照着工坊的门。林叔说：“人老了，手艺还能留着。”','留下来听他讲手艺','道别',{mood:3},'lampKeepsake']],
    xia:[['夏禾的行李','她把书装进箱子。“我想去外面读书，走前能替我看一眼书单吗？”','一起整理书单','祝她一路顺风',{knowledge:2},'xiaHelp'],['回来的书屋老师','书屋里的人抬起头，是夏禾。“我把外面的故事带回来了。”','一起整理返乡的书','聊聊后道别',{knowledge:3,mood:2},'homeBook']],
    chen:[['鸟食袋破了','陈伯正在拾散落的谷子，树上的鸟等着。','一起拾起来','坐着陪他一会',{body:-2,mood:2},'chenHelp'],['树下还留着位置','陈伯拍了拍长椅。“你看，它们又来了。”','陪他喂一次鸟','挥挥手',{mood:3},'birdNote']],
    yu:[['小店的账页','余青正对着一页旧账发愁。“这里是不是记重了？”','帮忙核对账目','让她慢慢想',{knowledge:2,money:2},'yuHelp'],['一直留着的糖','余青递来一小包糖。“总有人记得你的口味。”','收下这份心意','坐着聊聊',{mood:4},'sweetPaper']],
    zhou:[['没有地址的信','周岚拿着一封字迹模糊的信。“像是寄给旧工坊的。”','一起找回地址','先放在车站',{knowledge:2},'zhouHelp'],['晚到的回信','周岚叫住你。“信到了。有人终于等到回音。”','听听回信的故事','向他道谢',{mood:3},'replyLetter']],
    he:[['缺了一枚的棋子','何溪翻着棋盒。“少了一枚，摆不开了。”','陪他找棋子','看他摆个残局',{body:-2,mood:2},'heHelp'],['棋盘另一边','何溪把棋盒放好。“输赢记不住，人倒记得。”','约好下次再坐','聊两句',{mood:3},'chessPromise']],
    qiao:[['邻居门前的盆栽','乔安要出远门。“能替我照看这盆花吗？”','答应替他照看','祝他一路顺风',{body:-2},'qiaoHelp'],['回来时花还在','乔安站在熟悉的门口。“原来这里一直有人替我惦记。”','聊聊这些年的日子','陪他安静坐会',{mood:4},'pressedFlower']],
    wu:[['旅人的旧地图','旅人指着地图上淡掉的线。“你走过那条路吗？”','一起辨认旧路','听他讲旅行',{knowledge:2},'wuHelp'],['一次不约而同','又在车站遇到旅人。他笑了：“路总能把人带回来。”','留下一个小镇的故事','祝他旅途平安',{mood:3},'travelerMap']]
  };
  function memory(s,id){const prefix='npc:'+id+':',flags=s?.flags||[],met=flags.includes(prefix+'met'),help=flags.includes(prefix+'help'),complete=flags.includes(prefix+'done');return {metPlayer:met,playerHelpedMe:help,lostChessToPlayer:flags.includes(prefix+'chess'),complete,relation:met?(20+(flags.includes(prefix+'chat')?20:0)+(help?20:0)+(complete?25:0)):0};}
  function label(value){return ['陌生','认识','熟悉','亲近','重要的人'][Math.min(4,Math.floor(value/20))];}
  function available(s,id){if(!s||s.version!==2||s.phase!=='route'||!D.residents.some(d=>d.id===id&&!d.awayStages?.includes(s.stage)))return [];const m=memory(s,id),out=[];if(!m.metPlayer)return ['meet'];if(!s.flags.includes('npc:'+id+':chat'))out.push('chat');if(['chen','he'].includes(id)&&m.relation>=40&&!m.lostChessToPlayer)out.push('chess');if(s.stage>=1&&!s.flags.includes('npc:'+id+':decision'))out.push('help','decline');const decisionStage=Number(s.flags.find(f=>f.startsWith('npc:'+id+':decisionAt:'))?.split(':').at(-1)??1);if(s.stage>=3&&s.stage>=decisionStage+2&&s.flags.includes('npc:'+id+':decision')&&!m.complete)out.push('done');return out;}
  function apply(s,id,choice,moves){if(!available(s,id).includes(choice))return false;if(choice==='chess'){const chess=node?require('./gomoku-engine.js'):root.Gomoku,g=chess?.Game.restore(moves);if(!g?.over||g.winner!==1)return false;}const prefix='npc:'+id+':',d=D.residents.find(v=>v.id===id);let changes={};const before={...s.resources};const add=f=>{if(!s.flags.includes(f))s.flags.push(f);};if(choice==='chess'){add(prefix+'chess');changes={mood:2};}if(choice==='meet'||choice==='chat')add(prefix+(choice==='meet'?'met':'chat'));if(choice==='help'||choice==='decline'){add(prefix+'decision');add(prefix+'decisionAt:'+s.stage);if(choice==='help'){add(prefix+'help');add(stories[id][0][5]);changes=stories[id][0][4];}}if(choice==='done'){add(prefix+'done');changes=memory(s,id).playerHelpedMe?stories[id][1][4]:{mood:1};if(memory(s,id).playerHelpedMe)add(stories[id][1][5]);}for(const [key,value] of Object.entries(changes))s.resources[key]=Math.max(key==='money'?-100:0,Math.min(key==='money'?200:100,s.resources[key]+value));s.actions.push({kind:'resident',npc:id,choice,...(choice==='chess'?{moves:moves.map(m=>[...m])}:{})});s.living=true;if(['help','decline','done'].includes(choice))s.log.push({type:'resident',stage:s.stage,title:d.name+' · '+stories[id][choice==='done'?1:0][0],choice:choice==='help'?stories[id][0][2]:choice==='decline'?stories[id][0][3]:'再次相遇',story:choice==='done'&&!memory(s,id).playerHelpedMe?'当年错过的小事，如今已经过去。你们仍可以坐下来聊聊。':stories[id][choice==='done'?1:0][1],changes:Object.fromEntries(Object.keys(changes).map(key=>[key,s.resources[key]-before[key]])),success:true});return true;}
  const items={lampKeepsake:['旧灯的草图','林叔留下的手艺。'],homeBook:['返乡的书','夏禾带回的故事。'],birdNote:['喂鸟的小纸条','陈伯记下的几个老朋友。'],sweetPaper:['糖纸','小店里有人记得你的口味。'],replyLetter:['回信','一段迟到的回音。'],chessPromise:['棋局约定','何溪留出的另一边。'],pressedFlower:['压花','乔安家门前开过的花。'],travelerMap:['旅人的地图','一条通往再相遇的路。']};
  const api={stories,items,memory,label,available,apply};if(node)module.exports=api;else root.NPCEvents=api;
})(globalThis);
