(function(root){
  const node=typeof module!=='undefined'&&module.exports,D=node?require('./npc-data.js'):root.NPCData,T=node?require('./town-scene.js'):root.TownScene;
  function hash(seed,text){let n=seed>>>0;for(const c of text)n=Math.imul(n^c.charCodeAt(0),16777619)>>>0;return n/4294967296;}
  function profile(d,stage){return {age:d.ages[Math.min(4,stage)],coat:stage>=3?d.laterCoat:d.coat,role:stage>=3&&d.laterRole?d.laterRole:d.role,home:stage>=3&&d.laterHome?d.laterHome:d.home,away:d.awayStages?.includes(stage)||false};}
  function goal(d,time,seed,stage){const p=profile(d,stage);let entry=d.schedule[time.slot];if(time.slot===4&&d.evening){let roll=hash(seed,d.id+':'+time.day+':'+stage),chosen=d.evening.at(-1);for(const option of d.evening){roll-=option[2];if(roll<0){chosen=option;break;}}entry=chosen;}if(stage>=3&&d.laterSchedule)entry=d.laterSchedule[time.slot];const place=T.places.find(v=>v.id===(entry[0]==='home'?p.home:entry[0]));const offset=(D.residents.indexOf(d)%4-1.5)*18;return {x:place.x+offset,y:place.y+25+(D.residents.indexOf(d)%2)*14+Math.floor(D.residents.indexOf(d)/4)*18,place:place.id,behavior:entry[1]};}
  function create(seed=0,saved){return {seed:seed>>>0,actors:D.residents.map((d,i)=>{const old=saved?.actors?.find?.(v=>v.id===d.id),home=T.places.find(p=>p.id===d.home);return {id:d.id,x:T.walkable(old?.x,old?.y)?old.x:home.x+20+i*4,y:T.walkable(old?.x,old?.y)?old.y:home.y+28,token:'',path:[],behavior:'resting',facing:'down',gait:0,talk:Number.isFinite(old?.talk)?Math.max(0,Math.min(9,old.talk)):0,speech:typeof old?.speech==='string'?old.speech.slice(0,80):'',lastSocial:typeof old?.lastSocial==='string'?old.lastSocial.slice(0,40):''};})};}
  function tick(world,time,stage,dt,paused=false){if(paused)return;for(const a of world.actors){const d=D.residents.find(v=>v.id===a.id),p=profile(d,stage);a.away=p.away||(d.rare&&hash(world.seed,d.id+':visit:'+time.day+':'+stage)>.35);a.age=p.age;a.role=p.role;a.needs={rest:time.slot===5?'想休息':'精神尚好',food:time.slot===2?'该吃饭了':'不太饿',company:time.slot===4?'想坐着聊聊':'按自己的节奏'};a.coat=p.coat;if(a.away)continue;const token=time.day+':'+time.slot+':'+stage;if(a.token!==token){const g=goal(d,time,world.seed,stage);a.goal=g;a.path=T.planPath(a,g)||[];a.token=token;}
      if(a.talk>0){a.talk=Math.max(0,a.talk-dt);a.behavior='talking';continue;}a.speech='';const before={x:a.x,y:a.y},move=T.followPath(a,a.path,Math.max(0,dt)*80);a.x=move.position.x;a.y=move.position.y;a.path=move.path;const dx=a.x-before.x,dy=a.y-before.y;if(dx||dy){a.facing=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';a.gait+=Math.hypot(dx,dy)*.1;a.behavior='walking';}else a.behavior=a.goal.behavior;
    }
    for(let i=0;i<world.actors.length;i++)for(let j=i+1;j<world.actors.length;j++){const a=world.actors[i],b=world.actors[j],d=D.residents[i],key=time.day+':'+time.slot+':'+stage;if(a.away||b.away||a.path.length||b.path.length||a.talk||b.talk||a.lastSocial===key||b.lastSocial===key||!d.relationships[b.id]||Math.hypot(a.x-b.x,a.y-b.y)>64)continue;a.lastSocial=b.lastSocial=key;a.talk=b.talk=9;a.speech=d.id==='lin'&&b.id==='yu'?'山坡那条旧路，最近又有人走了。':'今天还是老样子？晚点坐坐。';b.speech=b.id==='chen'?'棋盘留着，来一局。':'嗯，日子慢慢过。';a.facing=a.x<b.x?'right':'left';b.facing=a.x<b.x?'left':'right';}
  }
  function snapshot(w){return {actors:w.actors.map(a=>({id:a.id,x:a.x,y:a.y,talk:a.talk,speech:a.speech,lastSocial:a.lastSocial}))};}
  function near(w,p,r=55){return w.actors.filter(a=>!a.away&&Math.hypot(a.x-p.x,a.y-p.y)<=r).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];}
  const api={hash,profile,goal,create,tick,snapshot,near};if(node)module.exports=api;else root.NPCSystem=api;
})(globalThis);
