const {test}=require('node:test'),assert=require('node:assert/strict'),N=require('../js/npc-system.js'),D=require('../js/npc-data.js'),G=require('../js/game-time.js'),T=require('../js/town-scene.js'),E=require('../js/life-rogue-engine.js'),V=require('../js/npc-events.js'),L=require('../js/npc-dialogue.js'),S=require('../js/game-save.js'),Mode=require('../js/display-mode.js');
const make=seed=>E.createMapped(seed,'ordinary',E.draft(seed).slice(0,2).map(t=>t.id));
function advance(s,stage){while(s.stage<stage&&s.phase!=='end'){const id=s.offers.find(id=>require('../js/life-rogue-data.js').events.find(e=>e.id===id).tag==='rest')||s.offers[0];E.pick(s,id);const event=E.currentEvent(s);let best=0,score=-Infinity;E.choices(s,event).forEach((c,i)=>{const delta=E.delta(s,c,event),v=delta.body*3+delta.mood;if(v>score){score=v;best=i;}});E.decide(s,best);}assert.equal(s.stage,stage);}
test('所有居民所有阶段和时段的目的地可达，移动全程合法',()=>{for(const stage of [0,1,2,3,4]){const w=N.create(12);for(let slot=0;slot<6;slot++){const time={day:1,slot,elapsed:0};N.tick(w,time,stage,0);for(const a of w.actors){if(a.away)continue;assert.ok(T.walkable(a.goal.x,a.goal.y));assert.ok(T.planPath(a,a.goal));}for(let frame=0;frame<1600;frame++){N.tick(w,time,stage,.025);for(const a of w.actors)assert.ok(T.walkable(a.x,a.y));}for(const a of w.actors)if(!a.away)assert.ok(Math.hypot(a.x-a.goal.x,a.y-a.goal.y)<1);}}});
test('日程按Seed和当天决定，刷新不改变目的地，暂停和显示模式不改变世界',()=>{const time={day:4,slot:4,elapsed:12},a=N.create(77),b=N.create(77);N.tick(a,time,1,.1);N.tick(b,time,1,.1);assert.deepEqual(a,b);const save=N.snapshot(a),restored=N.create(77,save);N.tick(restored,time,1,0);assert.deepEqual(restored.actors.map(a=>a.goal),a.actors.map(a=>a.goal));assert.deepEqual(N.snapshot(restored),save);const before=structuredClone(a);N.tick(a,time,1,1,true);Mode.resolve('mobile',{width:400});assert.deepEqual(a,before);assert.notDeepEqual(D.residents[0].evening.map(v=>v[0]),[]);});
test('记忆、故事条件、资源和物品可重放，每个事实和奖励只发生一次',()=>{const s=make(3);assert.equal(V.apply(s,'lin','help'),false);assert.ok(V.apply(s,'lin','meet'));assert.equal(V.apply(s,'lin','meet'),false);assert.ok(V.apply(s,'lin','chat'));assert.equal(V.label(V.memory(s,'lin').relation),'熟悉');assert.equal(V.apply(s,'lin','help'),false);advance(s,1);assert.ok(V.apply(s,'lin','help'));assert.ok(s.flags.includes('linHelp'));const before=structuredClone(s);assert.equal(V.apply(s,'lin','help'),false);assert.deepEqual(s,before);assert.equal(V.apply(s,'lin','done'),false);advance(s,3);assert.ok(V.apply(s,'lin','done'));assert.ok(s.flags.includes('lampKeepsake'));assert.equal(V.label(V.memory(s,'lin').relation),'重要的人');assert.deepEqual(E.restore(E.pack(s)),s);const bad=E.pack(s);bad.actions=[...bad.actions,{kind:'resident',npc:'lin',choice:'help'}];assert.equal(E.restore(bad),null);});
test('拒绝帮忙走不同的后续，未开启的秘密不会出现在对话里',()=>{const s=make(3),t=G.restore();const first=L.line('lin',s,t);assert.match(first,/新来的/);V.apply(s,'lin','meet');assert.notEqual(L.line('lin',s,t),first);assert.doesNotMatch(L.line('lin',s,t),/多亏/);advance(s,1);V.apply(s,'lin','decline');advance(s,3);V.apply(s,'lin','done');assert.equal(V.memory(s,'lin').playerHelpedMe,false);assert.ok(!s.flags.includes('lampKeepsake'));assert.deepEqual(E.restore(E.pack(s)),s);s.resources.body=10;assert.match(L.line('lin',s,t),/歇歇/);});
test('居民互相认识且自主聊天，学生离开后归来并换身份与住处',()=>{const w=N.create(9),time={day:1,slot:2,elapsed:0};N.tick(w,time,1,0);const lin=w.actors.find(a=>a.id==='lin'),yu=w.actors.find(a=>a.id==='yu');lin.x=yu.x=748;lin.y=yu.y=300;lin.path=yu.path=[];lin.talk=yu.talk=0;lin.lastSocial=yu.lastSocial='';N.tick(w,time,1,0);assert.ok(lin.talk>0);assert.match(lin.speech,/山坡/);assert.equal(N.profile(D.residents[1],2).away,true);assert.equal(N.profile(D.residents[1],3).away,false);assert.equal(N.profile(D.residents[1],3).home,'archive');assert.match(N.profile(D.residents[1],3).role,/老师/);});
test('新存档保存虚拟时间和位置，旧schema2位置保留，损坏居民安全重置',()=>{const s=make(7);V.apply(s,'yu','meet');const w=N.create(7),time={day:3,slot:4,elapsed:15};N.tick(w,time,1,.5);const raw=S.pack({run:s,map:{position:{x:748,y:300}},living:{time,world:N.snapshot(w),clue:true}}),restored=S.migrate(raw);assert.deepEqual(restored.living.time,time);assert.deepEqual(restored.living.world,N.snapshot(w));assert.deepEqual(restored.run,s);assert.deepEqual(S.migrate({...raw,schemaVersion:2}).map.position,{x:748,y:300});const corrupt=S.migrate({...raw,living:{time:{day:-1,slot:7,elapsed:NaN},world:{actors:[{id:'lin',x:900,y:620}]}}});assert.deepEqual(corrupt.living.time,G.restore());assert.ok(T.walkable(corrupt.living.world.actors[0].x,corrupt.living.world.actors[0].y));});
test('熟悉店主新增商业选项，旧玩法不变，关系选项恢复一致',()=>{const s=make(19),base=structuredClone(s);V.apply(s,'yu','meet');V.apply(s,'yu','chat');const area=s.mapOffers.find(o=>o.area==='commercial');E.arrive(s,area.area);const e=E.currentEvent(s);assert.equal(E.choices(s,e).length,e.choices.length+1);E.decide(s,e.choices.length);assert.deepEqual(E.restore(E.pack(s)),s);E.arrive(base,area.area);assert.equal(E.choices(base,E.currentEvent(base)).length,E.currentEvent(base).choices.length);});
test('棋友只记住合法胜局一次，刷新保留棋局记忆',()=>{const s=make(11);E.resident(s,'he','meet');E.resident(s,'he','chat');assert.equal(E.resident(s,'he','chess',[[0,0]]),false);const moves=[[7,3],[0,0],[7,4],[0,2],[7,5],[0,4],[7,6],[0,6],[7,7]];assert.ok(E.resident(s,'he','chess',moves));assert.equal(E.resident(s,'he','chess',moves),false);assert.equal(V.memory(s,'he').lostChessToPlayer,true);assert.deepEqual(E.restore(E.pack(s)),s);assert.match(L.line('he',s,G.restore()),/上回那盘/);});
test('晚认识的居民不会立刻产生多年后的回音',()=>{const s=make(3);advance(s,3);E.resident(s,'lin','meet');E.resident(s,'lin','help');assert.equal(E.resident(s,'lin','done'),false);assert.deepEqual(E.restore(E.pack(s)),s);});
test('深厚关系影响普通人生的叙事，但保留原来的八类结局和重放',()=>{let found=false;for(let seed=0;seed<30&&!found;seed++){const s=make(seed);advance(s,1);for(const id of ['lin','chen','qiao']){E.resident(s,id,'meet');E.resident(s,id,'chat');E.resident(s,id,'help');}while(s.phase!=='end'){E.pick(s,s.offers.find(id=>require('../js/life-rogue-data.js').events.find(e=>e.id===id).tag!=='rest')||s.offers[0]);E.decide(s,0);}if(s.ending==='ordinary'){found=true;assert.equal(s.remembered,true);assert.equal(E.endingInfo(s).name,'有人记得你');assert.match(E.summary(s),/有人记得你/);assert.deepEqual(E.restore(E.pack(s)),s);}}assert.ok(found);});
test('不用安排碰面位置，林叔与店主按日程走到小店就能谈起旧路',()=>{const w=N.create(5),t={day:0,slot:2,elapsed:0};let heard=false;for(let i=0;i<2000;i++){N.tick(w,t,1,.02);if(w.actors.find(a=>a.id==='lin').speech.includes('山坡'))heard=true;}assert.ok(heard);});
